const int INPUT_BG_COLOR = 0xffF5F5F5;
const int INPUT_HINT_COLOR = 0xffC1C1C1;
const int PRIMARY_COLOR = 0xff2A3D7D;
const int BUTTON_ENABLED_COLOR = 0xFFF5F5F5;
const int BLACK = 0xFFF5F5F5;
const int DIVIDER_COLOR = 0xFFDFDFDF;
const int DIVIDER_COLOR_PRIMARY = 0xFF4C5E9C;
const int ICON_SELCTED_COLOR = 0xFF556496;
